tweak

diff --git a/arch-wiki b/arch-wiki
--- a/arch-wiki
+++ b/arch-wiki
@@ -26,32 +26,31 @@ if [[ $# == 0 ]]; then
 	exit 0
 fi
 
-
+# parse options
 AWESOME_STYLE=1
-
-while [[ $# > 1 ]]
-do
-key="$1"
-
-case $key in
+while [[ $# > 0 ]]; do
+  case $1 in
     -h|--help)
     	usage
     	exit
     ;;
     -g|--grep)
-		shift
-		GLOBAL_SEARCH="$1"
-		shift
+		  shift
+		  GLOBAL_SEARCH="$1"
+		  shift
     ;;
     -n|--normal)
     	AWESOME_STYLE=0
     	shift
     ;;
-    *)
-            # unknown option
-            break
+    -l|--list)
+      find $ROOT
+      exit 0
     ;;
-esac
+    *)
+      break
+    ;;
+  esac
 done
 
 # grep
@@ -66,8 +65,8 @@ KEY=N/A
 NTH=0
 while [ -n "$1" ]; do
   case $1 in
-    -*) NTH=${1##-} ; AWESOME_STYLE=0    ;;
-    *)  KEY=$1          ;;
+    -*) NTH=${1##-}; AWESOME_STYLE=0 ;;
+    *)  KEY=$1 ;;
   esac
   shift
 done
@@ -76,40 +75,43 @@ done
 NTH=$((NTH - 1))
 DOC=( $(ls $ROOT | grep -i $KEY) )
 
+# open a doc
+open() {
+  $LESS -c 'set syntax=markdown' $ROOT/${DOC[$1]}
+  exit 0
+}
 
-# open document
+# no match
+if [[ ${#DOC[*]} == 0 ]]; then
+  echo "Can't find $KEY"
+  exit 1
+fi
+
+# single match or nth is specified
 if [[ ${#DOC[*]} == 1 ]] || [[ $NTH != -1 ]]; then
-  $LESS -c 'set syntax=markdown' $ROOT/${DOC[$NTH]}
+  open $NTH
 else
-  counter=0
-  for d in ${DOC[*]}; do
-    # check for interactive mode
+  # menu
+  for ((cnt=0; cnt<${#DOC[*]}; cnt ++)); do
     if [ $AWESOME_STYLE -eq 1  ] ; then 
-   		 echo "[$counter]" $d
-		 results[$counter]=$d
-		((counter++))
-   	else
-   		 echo $d
+   		 echo -n "[$((cnt+1))] "
    	fi
+   	echo ${DOC[$cnt]}
   done
 
   # now ask the user for number
   if [ $AWESOME_STYLE -eq 1 ] ; then
+    upto=${#DOC[*]}
 	  echo ; # just for nice formatting
 	  while true; do
-			read -p "Please choose a number from the list [1-9|q]: " input
+			read -p "Please choose a number from the list [1-$upto|q]: " input
 			case $input in
-				[Qq]* ) exit;;
-				[1-9]* ) 
-					if [ $input -le 0 ] || [ $input -lt $counter ] ; then
-							echo "Opening" ${results[$input]}; 
-							$LESS -c 'set syntax=markdown' $ROOT/${results[$input]};
-							break
-					else
-						echo "Invalid key."
-					fi
+				[Qq]*) exit;;
+				[1-$upto]*) 
+					echo "Opening" ${DOC[$input-1]};
+					open $(($input-1))
 					;;
-				* ) echo "Invalid option. Use q to quit.";;
+				*) echo "Invalid option. Use q to quit.";;
 			esac
 		done
 	fi
